### ISSUE TITLE
Can't serve file/pathnames including Japanese characters

### ISSUE THREAD

**Issue by kaervin** [snapframework/snap-core#246]
I am trying to serve some files via "serveDirectoryWith fancyDirectoryConfig",
using httpServe and the default config.
Outputting the Locale with getLocale shows me "en_US".
Requesting some files with non-Standard filenames, such as
"1. 赤いコート.mp3", returns with 
"No handler accepted "/static/files/1.%20%E8%B5%A4%E3%81%84%E3%82%B3%E3%83%BC%E3%83%88.mp3""
The file shows up with it's normal filename in the directory listing created with the fancyDirectoryConfig.
I am running this under Linux, the files come originally from a Windows install though (if this matters).

**Comment by gregorycollins** [comment]
FilePath encoding is a mess in Haskell :(

FilePaths are decoded from the query string by us as utf-8, and then re-encoded to String (as FilePath) to pass into the OS functions. This round-tripping is error prone to say the least.

The fix is usually to ensure that all of your locale parameters are set properly, and attempt to do that for you: https://github.com/snapframework/snap-server/blob/master/src/Snap/Http/Server.hs#L287

Try setting all of those LC_* environment variables as "en_US.utf-8".

**Comment by kaervin** [comment]
I fixed it, apparently there were some problems with my locale.
Thanks.
