### ISSUE TITLE
Dependency on MonadCatchIO-transformers needs to change to execptions?

### ISSUE THREAD

**Issue by afcowie** [snapframework/snap-core#256]
**http-streams** is [blocked](https://github.com/afcowie/http-streams/issues/96) porting to GHC 8 presently because **MonadCatchIO-transformers** is not in stackage nightly because its marked unmaintained. We need it for our test suite which uses Snap and a `catch` from there since MonadSnap depends on MonadCatchIO as a superclass. Apparently that's deprecated in favour of **exceptions**, wherein there is a MonadCatch with a `catch`.

Don't know if anyone has started trying to get Snap on board with the GHC 8 effort, but is this something we can change in the 0.9 series?

AfC

**Comment by sopvop** [comment]
Expetions don't fit here, because Snap can't be MonadMask, for same reasons that ExeptT can't. And MonadCatch is not enough.

It would be best to release 1.0 as it is. It certainly is production ready, I've been using it for two years now.
And leave comandline branch stuff for 1.1.

Since @gcollins can't spend much time on snap anymore, maybe someone else can update changelog and write short announcement? 

I can't do it myself because my English is not that good, and I no longer remember what's new in 1.0 besides io-streams

**Comment by hesiod** [comment]
I agree with @sopvop - it would be great to get 1.0 out of the door, since a whole lot of packages depend on Snap being GHC 8.0 compatible. As @afcowie mentioned, there is afcowie/http-streams#96 and, depending on that, dmjio/stripe#43. tibbe/ekg#53 also seems to wait for 1.0.

A detailed changelog would be better, yes, but looking briefly at the commits from the last two years, it seems that apart from the io-streams stuff most changes are fixes, version bound updates or minor documentation stuff (typos etc). I would suggest just getting Snap 1.0 released without too much bikeshedding about the changelog.

**Comment by perglr** [comment]
Any advice how to overcome this and compile now with GHC 8.0.x? Thx.

**Comment by mightybyte** [comment]
@perglr Github master is on 1.0, so if you build against that you should be able to get it working with GHC 8.  You may need to bump some version bounds along the way but I'm happy to accept pull requests for that.

**Comment by perglr** [comment]
Builds fine, thanks a lot! Hoping to have it on Hackage, soon.

**Comment by winterland1989** [comment]
> Exceptions don't fit here, because Snap can't be MonadMask, for same reasons that ExeptT can't. And MonadCatch is not enough.

I can't see why `MonadCatch` is not enough here?

**Comment by mightybyte** [comment]
Closing now that 1.0 is released
