### ISSUE TITLE
More precise routing

### ISSUE THREAD

**Issue by snap9** [snapframework/snap-core#266]
I'm noticing that a route like "/:foo/:bar/:baz" matches "/2016/12/01" (which is fine), but it also matches "/2016/12/01/asdf". Why? This is unexpected. How do I remedy this?

Also, is there a way to do more precise routing patterns with regular expressions?

**Comment by mightybyte** [comment]
The idea is that it matches whatever prefix you specify.  If you want exact matching, you can use the [`iftop` function](http://hackage.haskell.org/package/snap-core-1.0.1.0/docs/Snap-Core.html#v:ifTop).

Snap does not include regular expression based routing out of the box.

**Comment by snap9** [comment]
@mightybyte 

I'm guessing the purpose of matching only with prefixes is to get the fast `O(log n)` route search.

I notice I can customize things completely (including with regex if I want) using `rqURI` and `empty`. The upside is that it doesn't only match prefixes. The downside is that I lose the fast routing and go back to `O(n)`.

Is this the thinking behind it, or is there something else or more to it?

**Comment by gregorycollins** [comment]
O(log n) prefix routing is the reason behind the "route" combinator but it isn't the reason behind the matching behavior here, the other combinators (e.g. `dir`) behave this way also. This allows matching to compose:

```haskell
routeA, routeB1, routeB2, routeC :: Snap ()

site = route [ ("a", ifTop routeA)   -- matches on /a only
             , ("b", dir "1" routeB1 <|> dir "2" routeB2),  -- matches on /b/1(/...) and /b/2(/...)
             , ("c", routeC)  -- matches on any descendant
             ]

```

Re: `log n` routing with `route`: there's nothing magic about it, we split on '/' and walk a HashMap. If more than one route matches, they are combined using `<|>`. Have a look at the [implementation](https://github.com/snapframework/snap-core/blob/master/src/Snap/Internal/Routing.hs).

@snap9 you could do regex based routing efficiently, as long as the combinator you used combined `n` regexes into one DFA rather than combining using the `Alternative` instance. Matching in this case would actually be linear.
