### ISSUE TITLE
Add graceful shutdown on SIGTERM

### ISSUE THREAD

**Issue by mbucc** [snapframework/snap-core#270]
Don't shutdown server until existing client connections are closed.  Add a config flag, off by default.

Writing a signal handler is simple enough, but how do you count the number of open client connections?

**Comment by gregorycollins** [comment]
Don't bother with the signal handler, we already react to `ThreadKilled`. Active connections are managed by the TimeoutManager -- if you want to spend some time waiting for threads to die instead of killing them right away, the place is in `Session.hs` between killing the accept thread and calling `TM.stop`. TimeoutManager will need a few modifications:

  - add a "shutdown" mode -- when in shutdown mode, if the manager thread clears the active queue it should post to an MVar
  - add a "waitForConnections" which blocks on this MVar for at most K seconds

**Comment by mbucc** [comment]
Thanks for the detailed note.  I no longer have the inclination to work on this, so I'm going to close this ticket.
