### ISSUE TITLE
won't compile on 9.2.5

### ISSUE THREAD

**Issue by liamzee** [snapframework/snap-core#326]
Complains about parseTime being missing; and that's only in Data.Time.Compat or whatever it's called these days.

**Comment by praduca** [comment]
@liamzee are you on windows? I have the same problem, and found a modification on
`src/Snap/Internal/Http/Types.hs `
to solve a problem with windows dated from last month

**Comment by Chaddai** [comment]
Having checked, parseTime has been deprecated for quite a long time (recommandation : "use parseTimeM true instead") but definitely disappear in time-1.10 from 2020-03-13.

The cabal bound on time is <1.14 (and was already <1.11 4 years ago) so this should have been a problem for quite some time. Don't know how this got missed. The fix is quite easy though

**Comment by Chaddai** [comment]
To be more precise, parseTimeM was available since time-1.5 and parseTime was deprecated in the same release. So since 2014. 
This issue should in fact be closed since [this commit](https://github.com/snapframework/snap-core/commit/7b4cebbdfcad566bfdfba83f4c96c0b348c93011) fixed it. Let's just wait for the release.

**Comment by cydparser** [comment]
I've released 1.0.5.1
