### ISSUE TITLE
error: System.SendFile.Darwin: invalid argument (Socket is not connected)

### ISSUE THREAD

**Issue by spockz** [snapframework/snap-core#91]
When serving large static files you get the error below when you run out of file handles. I know you aren't supposed to do this with snap but nonetheless it should not crash the server.

> 14/Aug/2011:17:04:17 +0100] [192.168.25.85]: error: System.SendFile.Darwin: invalid argument (Socket is not connected)

**Comment by karls** [comment]
I'm having the same problem with Snap at the moment on Mac OSX. On Linux (Vagrant), it seems to work fine. Is this issue still open because it was never resolved fully?

On Mac OSX, no matter what I try, I get
```
A web handler threw an exception. Details:
TerminateSessionException sendfile: invalid argument (Socket is not connected)
```
But every once in a while, it does not throw the exception and actually works. It also seems to vary with the size of the file being served — smaller files (< 700kB) seem to work fine, but larger ones almost always throw an exception.

The variations I've tried:
```
do modifyResponse $ setContentType "video/webm"
   serveFile "<file location>"
---
do modifyResponse $ setContentType "video/webm"
   sendFile "<file location>"
---
do serveFile "<file location>"
---
do serveFileAs "video/webm" "<file location>"
```

I've also tried this by running the app in ghci (via DevelMain) and as a standalone executable.

Other info:
```
$ uname -a
Darwin siphon.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```
```
$ ulimit -n
256
```
Stackage: LTS-8.11
GHC: 8.0.2
Snap version: 1.0.0.1

I also built a quick Servant app just to double-check myself. It works fine with Servant (Warp/WAI) using `serveDirectoryWebApp`.

Any ideas what might be going wrong?

**Comment by gregorycollins** [comment]
I don't have a Mac box anymore so it's difficult for me to debug this. If the issue is with our sendfile() implementation for mac, then maybe we should remove it. Does it do this when you build with "-fportable"?

**Comment by karls** [comment]
Hey @gregorycollins!

Hurrah, using `-fportable` fixes this behaviour!
For posterity, I passed `--flag snap-server:portable` to `stack`.

Great stuff and thanks for a quick reply! It didn't occur to me to check the Cabal file for any compile flags.

**Comment by gregorycollins** [comment]
We're fixing this -- by turning sendfile off for OSX. My guess is that this worked back when I was using a Mac, but it's bitrotted for some reason in more recent OSX versions.

**Comment by miladz68** [comment]
I had the same issue on freebsd and I did the same as @karls  and it solved my problem. the solution as karls said is

> I passed --flag snap-server:portable to stack.

**Comment by miladz68** [comment]
Can I pass this 

> --flag snap-server:portable

  through cabal and not stack ?

**Comment by mightybyte** [comment]
Yes.  Do "cabal install snap -fportable".

**Comment by miladz68** [comment]
I didn't ask the question properly.
I meant to ask: Can I pt this paramter in the cabal file so I don't have to pass it every time I want to build?

**Comment by hvr** [comment]
@miladz68 no, that's intentionally not supported by the `.cabal` spec 

However, you can persist flag settings ("constraints") either in your `~/.cabal/config` file or in your per-project `cabal.project` file by adding a line like

    constraints: snap-server +portable

See also http://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-constraints
